name: poke_tiktok_flutter
description: Ejemplo de implementación de la Poke API mediante Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  either_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Pokemon-Classic
      fonts:
        - asset: assets/fonts/pokemon_classic.ttf

